CREATE ROLE $LIFERAY_USER WITH LOGIN ENCRYPTED PASSWORD '${LIFERAY_PASS}' CREATEDB;
CREATE DATABASE bibbox WITH OWNER postgres TEMPLATE template0 ENCODING 'UTF8';
CREATE SCHEMA lportal AUTHORIZATION $LIFERAY_USER;
GRANT ALL PRIVILEGES ON DATABASE bibbox TO $LIFERAY_USER;
ALTER ROLE $LIFERAY_USER SET search_path TO lportal;
